_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 54
                - 55
            "2":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 54
                - 55
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.1
            "6": 4.44.2
            "8":
                - 1
                - 5
            "12": 0.18.1
            "13": darwin-arm64
architecture:
    value: CF
batch_size:
    value: 64
betas:
    value:
        - 0.9
        - 0.999
dataset:
    value: Yelp
learning_rate:
    value: 0.001
num_epochs:
    value: 1
rank:
    value: 32
