_wandb:
    value:
        cli_version: 0.18.1
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 54
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 49
                - 53
                - 54
                - 55
            "3":
                - 1
                - 2
                - 16
                - 23
                - 55
            "4": 3.12.3
            "5": 0.18.1
            "6": 4.44.2
            "8":
                - 1
                - 5
            "12": 0.18.1
            "13": darwin-arm64
architecture:
    value: CF
batch_size:
    value: 6000
betas:
    value:
        - 0.9
        - 0.999
dataset:
    value: Yelp
descr:
    value: ' added weight decay'
learning_rate:
    value: 0.001
model_architecture:
    value: |-
        CFmodel(
          (user_emb): Embedding(287116, 10)
          (bus_emb): Embedding(148523, 10)
          (numerical_layer): Sequential(
            (0): Linear(in_features=5, out_features=10, bias=True)
            (1): ReLU()
            (2): BatchNorm1d(10, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
          )
          (fc_layers): Sequential(
            (0): Linear(in_features=30, out_features=128, bias=True)
            (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
            (2): ReLU()
            (3): Dropout1d(p=0.2, inplace=False)
            (4): Linear(in_features=128, out_features=1, bias=True)
          )
        )
num_epochs:
    value: 20
rank:
    value: 10
weight_decay:
    value: 0.01
